/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118288-g8bd66a8c95-20250112"
#endif /* AVUTIL_FFVERSION_H */
