#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#
#%%% CONFIGURATION %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#

[private]
@default:
    just --list --unsorted --list-prefix '‧‧‧‧ '

GREEN   :=  `printf '\e[92m'`
NC      :=  `printf '\e[0m'`

#==============================================================================#
#=== BUILD ====================================================================#

#build project
@build:
    make DEBUG=1

#rebuild project
@re: clean build

#clean project
@clean:
    make fclean
    make -f tests/greatest.mk fclean

#==============================================================================#
#==== TESTS ===================================================================#

#run all tests
@test: unit lint
    echo "{{GREEN}}TESTS OK!{{NC}}"

#**** LINT ********************************************************************#

#run static analysis (norminette)
@lint:
	fd	.								\
		-e .c							\
		-E '*.test.c'					\
		src								\
										\
		-e .h							\
		-E 'greatest.h'					\
		include							\
										\
		-X norminette					\
			| { ! grep Error; }

#**** UNIT ********************************************************************#

#run unit tests
@unit:
    make -f tests/greatest.mk
    ./tests/greatest-run ./test
